<?php
/**
 * Copyright © Trusted Shops SE. All rights reserved.
 * See LICENSE file for license details.
 */
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\ProductPage;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var Product $product */
$product = $productViewModel->getProduct();

if (!$product->getDescription()) {
    return;
}

$cssClasses = $block->getData('css_classes') ?? 'prose';

?>
<div class="<?= $escaper->escapeHtmlAttr($cssClasses) ?>">
    <?= $productViewModel->productAttributeHtml($product, $product->getDescription(), 'description') ?>

    <?= $block->getChildHtml(); ?>
</div>
